# -*- coding: utf-8 -*-
"""autoarima.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FlE4ktcJCOFRFMazI2PNZfKtniROqSBA
"""

#!pip install pmdarima

import pandas as pd
import numpy as np
import math
import time
from datetime import datetime
from pmdarima.arima import auto_arima
from sklearn.model_selection import train_test_split

def prediction_autoarima(df, metrics):
  #separates 80% of this data
  training_data_len = math.floor(len(df)*.8)

  ##CPU
  #creating a training dataset
  train = pd.DataFrame(df[0:training_data_len]['timestamp'])
  train[metrics] = df[0:training_data_len][metrics]
  train.set_index('timestamp',inplace = True)

  #creating the test base
  test = pd.DataFrame(df[training_data_len+1:]['timestamp'])
  test[metrics] = df[training_data_len+1:][metrics]
  test.set_index('timestamp',inplace = True)

  model = auto_arima(train, 
                   start_P=1, 
                       start_q=1, 
                       max_p=3, 
                       max_q=3, 
                       m=5, 
                       sazonal=True, 
                       d=None, 
                       D=1, 
                       trace=True, 
                       error_action='ignore', 
                       suppress_warnings=True, 
                       stepwise=True)

  model.fit(train)

  predictions = model.predict(n_periods = len(test))
  predictions = pd.DataFrame(predictions, index = test.index, columns=[metrics])
  predictions = predictions.fillna(0)
  
  return predictions[metrics], test[metrics]